### PR TITLE
mnist: use mirror only when original server is not available

### LINKED ISSUE #195: mnist: CI has failed with 403 forbidden error
CI (macos, ubuntu and windows) has failed:
- https://github.com/red-data-tools/red-datasets/actions/runs/9532177771/job/26273996707#step:8:1434
    > Error: test: #each(MNISTTest::Normal::test): Net::HTTPClientException: 403: Forbidden: http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz
/Users/runner/work/red-datasets/red-datasets/lib/datasets/downloader.rb:163:in `block (2 levels) in start_http'
/Users/runner/hostedtoolcache/Ruby/3.3.3/arm64/lib/ruby/3.3.0/net/http.rb:2353:in `block in transport_request'
/Users/runner/hostedtoolcache/Ruby/3.3.3/arm64/lib/ruby/3.3.0/net/http/response.rb:320:in `reading_body'
/Users/runner/hostedtoolcache/Ruby/3.3.3/arm64/lib/ruby/3.3.0/net/http.rb:2352:in `transport_request'
/Users/runner/hostedtoolcache/Ruby/3.3.3/arm64/lib/ruby/3.3.0/net/http.rb:2306:in `request'
/Users/runner/work/red-datasets/red-datasets/lib/datasets/downloader.rb:149:in `block in start_http'
/Users/runner/hostedtoolcache/Ruby/3.3.3/arm64/lib/ruby/3.3.0/net/http.rb:1570:in `start'
/Users/runner/work/red-datasets/red-datasets/lib/datasets/downloader.rb:145:in `start_http'
/Users/runner/work/red-datasets/red-datasets/lib/datasets/downloader.rb:50:in `block in download'
/Users/runner/work/red-datasets/red-datasets/lib/datasets/downloader.rb:128:in `block in synchronize'
<internal:kernel>:187:in `loop'
/Users/runner/work/red-datasets/red-datasets/lib/datasets/downloader.rb:98:in `synchronize'
/Users/runner/work/red-datasets/red-datasets/lib/datasets/downloader.rb:34:in `download'
/Users/runner/work/red-datasets/red-datasets/lib/datasets/dataset.rb:38:in `download'
/Users/runner/work/red-datasets/red-datasets/lib/datasets/mnist.rb:49:in `each'
/Users/runner/work/red-datasets/red-datasets/test/test-mnist.rb:70:in `each'
/Users/runner/work/red-datasets/red-datasets/test/test-mnist.rb:70:in `to_a'
/Users/runner/work/red-datasets/red-datasets/test/test-mnist.rb:70:in `block (3 levels) in <class:MNISTTest>'
- https://github.com/red-data-tools/red-datasets/actions/runs/9532177771/job/26273996776#step:8:1433
- https://github.com/red-data-tools/red-datasets/actions/runs/9532177771/job/26273996879#step:8:1451

Should we use a [mirror site](https://ossci-datasets.s3.amazonaws.com/mnist/) instead of [original site](http://yann.lecun.com/exdb/mnist/)?

See also:
https://github.com/oreilly-japan/deep-learning-from-scratch/issues/81

### PR DESCRIPTION
**Pull request by tikkss**
MNIST's original server is sometimes refusing to provide the requested
resource. So, we use the mirror server only when the original server is
refusing it.

Moreover this includes the following changes.

- Support fallback in Downloader

Fixes GH-195.

### CODE REVIEW

**Comment by tikkss** [comment]
Some tests have failed. I would like to fix them in a separate pull request.

File: lib/datasets/mnist.rb [hunk 1]
```diff
@@ -5,6 +5,7 @@
 module Datasets
   class MNIST < Dataset
     BASE_URL = "http://yann.lecun.com/exdb/mnist/"
+    FALLBACK_URL = "https://ossci-datasets.s3.amazonaws.com/mnist/"
```
Comment (kou) [inline lib/datasets/mnist.rb:8]: This may be used by subclasses. How about introducing `#base_urls` instead?

```diff
diff --git a/lib/datasets/fashion-mnist.rb b/lib/datasets/fashion-mnist.rb
index 9e5bcf6..194758f 100644
--- a/lib/datasets/fashion-mnist.rb
+++ b/lib/datasets/fashion-mnist.rb
@@ -2,9 +2,13 @@ require_relative 'mnist'
 
 module Datasets
   class FashionMNIST < MNIST
-    BASE_URL = "http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/"
-
     private
+    def base_urls
+      [
+        "http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/",
+      ]
+    end
+
     def dataset_name
       "Fashion-MNIST"
     end
diff --git a/lib/datasets/kuzushiji-mnist.rb b/lib/datasets/kuzushiji-mnist.rb
index 344bf06..9aa69ff 100644
--- a/lib/datasets/kuzushiji-mnist.rb
+++ b/lib/datasets/kuzushiji-mnist.rb
@@ -2,9 +2,13 @@ require_relative 'mnist'
 
 module Datasets
   class KuzushijiMNIST < MNIST
-    BASE_URL = "http://codh.rois.ac.jp/kmnist/dataset/kmnist/"
-
     private
+    def base_urls
+      [
+        "http://codh.rois.ac.jp/kmnist/dataset/kmnist/",
+      ]
+    end
+
     def dataset_name
       "Kuzushiji-MNIST"
     end
diff --git a/lib/datasets/mnist.rb b/lib/datasets/mnist.rb
index b07aa4e..9185019 100644
--- a/lib/datasets/mnist.rb
+++ b/lib/datasets/mnist.rb
@@ -4,8 +4,6 @@ require_relative "dataset"
 
 module Datasets
   class MNIST < Dataset
-    BASE_URL = "http://yann.lecun.com/exdb/mnist/"
-
     class Record < Struct.new(:data, :label)
       def pixels
         data.unpack("C*")
@@ -27,7 +25,7 @@ module Datasets
 
       @metadata.id = "#{dataset_name.downcase}-#{type}"
       @metadata.name = "#{dataset_name}: #{type}"
-      @metadata.url = self.class::BASE_URL
+      @metadata.url = base_urls.first
       @metadata.licenses = licenses
       @type = type
 
@@ -44,7 +42,7 @@ module Datasets
 
       image_path = cache_dir_path + target_file(:image)
       label_path = cache_dir_path + target_file(:label)
-      base_url = self.class::BASE_URL
+      base_url = base_urls.first
 
       download(image_path, base_url + target_file(:image))
       download(label_path, base_url + target_file(:label))
@@ -53,6 +51,13 @@ module Datasets
     end
 
     private
+    def base_urls
+      [
+        "http://yann.lecun.com/exdb/mnist/",
+        "https://ossci-datasets.s3.amazonaws.com/mnist/",
+      ]
+    end
+
     def licenses
       []
     end
```

File: lib/datasets/mnist.rb [hunk 2]
```diff
@@ -45,9 +46,26 @@ def each(&block)
...
+
+      begin
+        download(image_path, base_url + target_file(:image))
+      rescue Net::HTTPClientException => error
+        if error.response.code == "403"
+          download(image_path, fallback_url + target_file(:image))
+        else
+          raise error
+        end
+      end
```
Comment (kou) [inline lib/datasets/mnist.rb:59]: Can we do this in `download`?

```ruby
      download(image_path,
               *base_urls.collect {|base_url| base_url + target_file(:image)})
      download(label_path,
               *base_urls.collect {|base_url| base_url + target_file(:label)})
```

File: lib/datasets/mnist.rb (hunk 1 above)
Comment (tikkss) [reply lib/datasets/mnist.rb:8]: I missed used by subclasses. Thanks! I fixed it.

File: lib/datasets/mnist.rb (hunk 2 above)
Comment (tikkss) [reply lib/datasets/mnist.rb:59]: Thanks for your suggestion! How about this?:

```diff
diff --git a/lib/datasets/dataset.rb b/lib/datasets/dataset.rb
index 20b5a4e..d7fdc00 100644
--- a/lib/datasets/dataset.rb
+++ b/lib/datasets/dataset.rb
@@ -33,9 +33,13 @@ module Datasets
       @cache_path ||= CachePath.new(@metadata.id)
     end

-    def download(output_path, url, &block)
-      downloader = Downloader.new(url)
-      downloader.download(output_path, &block)
+    def download(output_path, *urls, &block)
+      urls.each do |url|
+        downloader = Downloader.new(url)
+        downloader.download(output_path, &block)
+      rescue Net::HTTPClientException => error
+        pp error # I didn't know what to do here...
+      end
     end

     def extract_bz2(bz2)
diff --git a/lib/datasets/mnist.rb b/lib/datasets/mnist.rb
index c4918e9..90a2cf2 100644
--- a/lib/datasets/mnist.rb
+++ b/lib/datasets/mnist.rb
@@ -42,27 +42,11 @@ module Datasets

       image_path = cache_dir_path + target_file(:image)
       label_path = cache_dir_path + target_file(:label)
-      base_url = self.class::BASE_URL
-      fallback_url = self.class::FALLBACK_URL
-
-      begin
-        download(image_path, base_url + target_file(:image))
-      rescue Net::HTTPClientException => error
-        if error.response.code == "403"
-          download(image_path, fallback_url + target_file(:image))
-        else
-          raise error
-        end
-      end
-      begin
-        download(label_path, base_url + target_file(:label))
-      rescue Net::HTTPClientException => error
-        if error.response.code == "403"
-          download(label_path, fallback_url + target_file(:label))
-        else
-          raise error
-        end
-      end
+
+      download(image_path,
+               *base_urls.collect { |base_url| base_url + target_file(:image) })
+      download(label_path,
+               *base_urls.collect { |base_url| base_url + target_file(:label) })

       open_data(image_path, label_path, &block)
     end
```

Comment (tikkss) [reply lib/datasets/mnist.rb]: I implemented in [784a1d1](https://github.com/red-data-tools/red-datasets/pull/196/commits/784a1d14abba507bcc9a161085562bc02fa56352). Could you check this change?

File: lib/datasets/dataset.rb [hunk 3]
```diff
@@ -33,9 +33,21 @@ def cache_path
       @cache_path ||= CachePath.new(@metadata.id)
     end
 
-    def download(output_path, url, &block)
-      downloader = Downloader.new(url)
-      downloader.download(output_path, &block)
+    def download(output_path, *urls, &block)
```
Comment (kou) [inline lib/datasets/dataset.rb:36]: How about requiring at least one URL?

```suggestion
    def download(output_path, url, *fallback_urls, &block)
      urls = [url] + fallback_urls
```

File: lib/datasets/dataset.rb [hunk 4]
```diff
@@ -33,9 +33,21 @@ def cache_path
...
+      urls.each do |url|
+        downloader = Downloader.new(url)
+        downloader.download(output_path, &block)
+        return
+      rescue Net::HTTPClientException => error
+        if urls.last != url
+          message = "site is not available: " +
+                    "#{error.class}: #{error.message}: " +
+                    "Attempting to download from an alternative site"
```
Comment (kou) [inline lib/datasets/dataset.rb:45]: We should include the failed URL and fallback URL to be tried for easy to debug.

File: lib/datasets/dataset.rb [hunk 5]
```diff
@@ -33,9 +33,21 @@ def cache_path
...
+          $stderr.puts(message)
+        else
+          raise error
+        end
+      end
```
Comment (kou) [inline lib/datasets/dataset.rb:50]: Sorry but can we do this in `Downloader`?
We will extract `Downloader` to https://github.com/red-data-tools/red-datastock for easy to share.

File: lib/datasets/dataset.rb (hunk 3 above)
Comment (tikkss) [reply lib/datasets/dataset.rb:36]: I agree, at least one URL should be required.

File: lib/datasets/dataset.rb (hunk 4 above)
Comment (tikkss) [reply lib/datasets/dataset.rb:45]: I agree, including the failed URL and fallback URL will make debugging easier. I would like to think a debug friendly message.

File: lib/datasets/dataset.rb (hunk 5 above)
Comment (tikkss) [reply lib/datasets/dataset.rb:50]: Yes. I would like to send a this patch to https://github.com/red-data-tools/red-datastock

File: lib/datasets/dataset.rb (hunk 3 above)
Comment (tikkss) [reply lib/datasets/dataset.rb]: I implemented in aafbddb.

File: lib/datasets/dataset.rb (hunk 4 above)
Comment (tikkss) [reply lib/datasets/dataset.rb]: I implemented in d5cf668

File: lib/datasets/dataset.rb (hunk 5 above)
Comment (kou) [reply lib/datasets/dataset.rb]: Ah, we don't need to change https://github.com/red-data-tools/red-datastock for now.
It's not ready yet.
We may reconstruct it later.

Comment (tikkss) [reply lib/datasets/dataset.rb]: Oh, I'm so sorry. I'll try not to send a patch.

File: lib/datasets/dataset.rb (hunk 4 above)
Comment (kou) [reply lib/datasets/dataset.rb]: Mixing `:` and `..` as separator isn't a good idea.
How about 'fallback: <http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz> -> <https://ossci-datasets.s3.amazonaws.com/mnist/t10k-labels-idx1-ubyte.gz>` or something?

Comment (tikkss) [reply lib/datasets/dataset.rb]: Thanks for your suggestion. `->` separator is good idea! and angle brackets is used to delimit the boundaries of the URL in <https://www.ietf.org/rfc/rfc1738.txt>. It's reasonable!

> For this purpose,
   is recommended that angle brackets ("<" and ">"), along with the
   prefix "URL:", be used to delimit the boundaries of the URL.

Comment (tikkss) [reply lib/datasets/dataset.rb]: I implemented in 01e273e. e.g. : `403 Forbidden: fallback: <http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz> -> <https://ossci-datasets.s3.amazonaws.com/mnist/t10k-labels-idx1-ubyte.gz>`

File: lib/datasets/dataset.rb [hunk 6]
```diff
@@ -33,9 +33,23 @@ def cache_path
       @cache_path ||= CachePath.new(@metadata.id)
     end
 
-    def download(output_path, url, &block)
-      downloader = Downloader.new(url)
-      downloader.download(output_path, &block)
+    def download(output_path, url, *fallback_urls, &block)
+      urls = [url] + fallback_urls
+      urls.each_with_index do |url, idx|
```
Comment (kou) [inline lib/datasets/dataset.rb:38]: `i` or `index` is better than `idx`:

```suggestion
      urls.each_with_index do |url, index|
```

File: lib/datasets/dataset.rb [hunk 7]
```diff
@@ -33,9 +33,23 @@ def cache_path
...
+        downloader = Downloader.new(url)
+        downloader.download(output_path, &block)
+        return
+      rescue Net::HTTPClientException => error
+        if urls.last != url
+          failed_url = "<#{url}>"
+          fallback_url = "<#{urls[idx + 1]}>"
+          message = "#{error.response.code} #{error.response.message}: " +
+                    "fallback: #{failed_url} -> #{fallback_url}"
```
Comment (kou) [inline lib/datasets/dataset.rb:47]: `XXX_url` should not have `<` and `>` because `<` and `>` aren't URL:

```suggestion
          failed_url = url
          fallback_url = urls[idx + 1]
          message = "#{error.response.code} #{error.response.message}: " +
                    "fallback: <#{failed_url}> -> <#{fallback_url}>"
```

File: lib/datasets/dataset.rb [hunk 8]
```diff
@@ -33,9 +33,23 @@ def cache_path
...
+          $stderr.puts(message)
+        else
+          raise error
```
Comment (kou) [inline lib/datasets/dataset.rb:50]: We should not specify `error` here to propagate the raised exception as-is:

```suggestion
          raise
```

File: lib/datasets/dataset.rb (hunk 6 above)
Comment (tikkss) [reply lib/datasets/dataset.rb:38]: I agree, using `i` or `index` is clearer than `idx`.

File: lib/datasets/dataset.rb (hunk 7 above)
Comment (tikkss) [reply lib/datasets/dataset.rb:47]: I agree, `XXX_url` should not have `<` and `>` because `<` and `>` aren't part of the URL.

File: lib/datasets/dataset.rb (hunk 8 above)
Comment (tikkss) [reply lib/datasets/dataset.rb:50]: Oh, I didn't know. Thanks for your suggestion!

https://docs.ruby-lang.org/en/3.3/Kernel.html#method-i-raise
> With no arguments, raises the exception in `$!` or raises a [RuntimeError](https://docs.ruby-lang.org/en/3.3/RuntimeError.html) if `$!` is `nil`.

**Comment by tikkss** [comment]
Thank you so much for a lot of suggestions! @kou 

It has been an exciting and enjoyable experience.

I've resolved all your reviewed points, so could you review it again?

File: lib/datasets/dataset.rb [hunk 9]
```diff
@@ -33,9 +33,23 @@ def cache_path
...
+        if urls.last != url
+          failed_url = url
+          fallback_url = urls[index + 1]
+          message = "#{error.response.code} #{error.response.message}: " +
+                    "fallback: <#{failed_url}> -> <#{fallback_url}>"
+          $stderr.puts(message)
+        else
+          raise
+        end
+      end
```
Comment (kou) [inline lib/datasets/dataset.rb:52]: Could you try moving this implementation to `Downloader`?

Comment (tikkss) [reply lib/datasets/dataset.rb:52]: Sure! I'll try it.

Comment (tikkss) [reply lib/datasets/dataset.rb]: I’ve moved the implementation to the `Downloader` and extracted the URL parsing and validation logic to a method.

I’ve also updated the pull request description. Could you review it again?

File: lib/datasets/downloader.rb [hunk 10]
```diff
@@ -155,6 +160,16 @@ def download(output_path, &block)
             $stderr.puts "Redirect to #{url}"
             return start_http(url, headers, limit - 1, &block)
           else
+            if response.is_a?(Net::HTTPForbidden)
+              fallback_url = @fallback_urls.shift
```
Comment (kou) [inline lib/datasets/downloader.rb:164]: Can we avoid changing `@fallback_urls` destructively?
If we change `@fallback_urls` destructively, users can't call `#download` multiple times for the same `Downloader`.

Comment (tikkss) [reply lib/datasets/downloader.rb:164]: I didn't notice users can't call `#download` multiple times for the same `Downloader`.
I will try to avoid changing `@fallback_urls` destructively.
Thanks!

Comment (tikkss) [reply lib/datasets/downloader.rb]: I've implemented in f92ec1a. But I have some concerns.

If the same URL is specified in `fallback_urls`, it can result in an infinite loop:

```diff
diff --git a/lib/datasets/mnist.rb b/lib/datasets/mnist.rb
index 9129be9..a3e6230 100644
--- a/lib/datasets/mnist.rb
+++ b/lib/datasets/mnist.rb
@@ -54,6 +54,8 @@ module Datasets
     private
     def base_urls
       [
+        "http://yann.lecun.com/exdb/mnist/",
+        "http://yann.lecun.com/exdb/mnist/",
         "http://yann.lecun.com/exdb/mnist/",
         "https://ossci-datasets.s3.amazonaws.com/mnist/",
       ]
```

```console
❯ ruby -I lib test/run-test.rb -t MNISTTest
Loaded suite test
Started
|403: Forbidden: fallback: <http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz> -> <http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz>
403: Forbidden: fallback: <http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz> -> <http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz>
403: Forbidden: fallback: <http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz> -> <http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz>
(snip)
```

While I believe this is a rare case, do we need to consider this scenario?

If we do need to consider it, I think we might need to use an instance variable like `@fallback_index`.
But, this could make the code less readable.

Comment (kou) [reply lib/datasets/downloader.rb]: How about using argument instead?

```diff
diff --git a/lib/datasets/downloader.rb b/lib/datasets/downloader.rb
index fac8a13..3449855 100644
--- a/lib/datasets/downloader.rb
+++ b/lib/datasets/downloader.rb
@@ -40,7 +40,7 @@ module Datasets
             headers["Range"] = "bytes=#{start}-"
           end
 
-          start_http(@url, headers) do |response|
+          start_http(@url, @fallback_urls, headers) do |response|
             if response.is_a?(Net::HTTPPartialContent)
               mode = "ab"
             else
@@ -140,7 +140,7 @@ module Datasets
       end
     end
 
-    private def start_http(url, headers, limit = 10, &block)
+    private def start_http(url, fallback_urls, headers, limit = 10, &block)
       if limit == 0
         raise TooManyRedirects, "too many redirections: #{url}"
       end
@@ -158,17 +158,15 @@ module Datasets
           when Net::HTTPRedirection
             url = URI.parse(response[:location])
             $stderr.puts "Redirect to #{url}"
-            return start_http(url, headers, limit - 1, &block)
+            return start_http(url, fallback_urls, headers, limit - 1, &block)
           else
             if response.is_a?(Net::HTTPForbidden)
-              index = @fallback_urls.index(url)
-              fallback_index = index.nil? ? 0 : index + 1
-              fallback_url = @fallback_urls[fallback_index]
-              unless fallback_url.nil?
+              next_url, *rest_fallback_urls = fallback_urls
+              if next_url
                 message = "#{response.code}: #{response.message}: " +
-                          "fallback: <#{url}> -> <#{fallback_url}>"
+                          "fallback: <#{url}> -> <#{next_url}>"
                 $stderr.puts(message)
-                return start_http(fallback_url, headers, limit, &block)
+                return start_http(next_url, rest_fallback_urls, headers, &block)
               end
             end
 
```

Comment (tikkss) [reply lib/datasets/downloader.rb]: Wow! Using argument, we don't have an instance variable, and the code became to readable.

I will implement it. Thank you so much!

Comment (tikkss) [reply lib/datasets/downloader.rb]: I've implemented in 7b78fc2. Could you review it again?

**Comment by kou** [comment]
Thanks!

**Comment by tikkss** [comment]
Thanks for your review!
